### ISSUE TITLE
fix ClientConnectorCertificateError

### ISSUE THREAD

**Issue by zakhar-petukhov** [nessshon/pytonapi#1]
1) Add ssl=False to the AsyncTonapiClient class, to the _request(...) method.

```
async with await session.get(f"{self.__base_url}{method}",
                      params=params, ssl=False
                      ) as response:
```

2) Write a description that your library only works with python above 3.10

Thanks 👍

**Comment by nessshon** [comment]
Closing this issue as completed.

The necessary changes have been made to the AsyncTonapiClient class by adding ssl=False to the _request(...) method.
Additionally, support for Python 3.7+ has been added to the library. The _request(...) method has been replaced with _get(...) and _post(...) methods have been added to send requests for methods that are not included in the library.

Thank you for bringing this to our attention! 👍
